server:
    port: 9091

spring:

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 111

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
                hibernate:
                    enable_lazy_load_no_trans: true
